# Generated by Django 4.0 on 2022-01-03 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cart_products_options'),
        ('carts', '0002_rename_user_id_cart_user_alter_cart_products_options'),
    ]

    operations = [
    ]
