# Generated by Django 4.0 on 2022-01-02 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('carts', '0002_alter_cart_products_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products_options',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productoption'),
        ),
    ]
