# Generated by Django 4.0 on 2022-01-03 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_order_status_order_order_status_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_status_id',
            new_name='order_status',
        ),
    ]
