# Generated by Django 4.0 on 2022-01-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productoption',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productoption',
            old_name='size_id',
            new_name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(through='products.ProductOption', to='products.Size'),
        ),
    ]
