# Generated by Django 4.0 on 2022-01-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(related_name='productsize', through='products.ProductOption', to='products.Size'),
        ),
    ]
