# Generated by Django 4.0 on 2022-01-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(through='products.ProductOption', to='products.Size'),
        ),
    ]
